### ISSUE TITLE
Support for multiple GPUs

### ISSUE THREAD

**Issue by xsacha** [MccreeZhao/QAMFace#2]
I noticed there's no code to set which GPUs are to be used. There's also no synchronisation code in the loss function for multiple GPUs.

How did you train it on 4 GPUs without this, or is it no longer needed in modern PyTorch?

I modified your QAMFace to include the support:

```Python
        if self.device_id == None:
            kernel_norm = l2_norm(self.weight, axis=0)
            cos_theta = torch.mm(embbedings, kernel_norm)
        else:
            x = embbedings
            sub_kernels = torch.chunk(self.weight, len(self.device_id), dim=1)
            temp_x = x.cuda(self.device_id[0])
            kernel_norm = l2_norm(sub_kernels[0], axis = 0).cuda(self.device_id[0])
            cos_theta = torch.mm(temp_x, kernel_norm)
            for i in range(1, len(self.device_id)):
                temp_x = x.cuda(self.device_id[i])
                kernel_norm = l2_norm(sub_kernels[i], axis = 0).cuda(self.device_id[i])
                cos_theta = torch.cat((cos_theta, torch.mm(temp_x, kernel_norm).cuda(self.device_id[0])), dim=1)
```

**Comment by MccreeZhao** [comment]
Hi, thanks for your help.
Since the loss function is paralleled. I think PyTorch may automatically deal with it.

**Comment by xsacha** [comment]
Thanks

**Comment by xsacha** [comment]
Looks like face.evolve has more balanced memory usage due to this change.
I can have two cards using 11.2/12GB each with that change.
However, with this repository, I get one card using 12.0 (and running out of memory) and the other using 11.0, at the same batch size (192).

face.evolve:
|    0      8204      C   python3                                    11235MiB |
|    1      8204      C   python3                                    10039MiB |
+-----------------------------------------------------------------------------+
