### ISSUE TITLE
focal loss

### ISSUE THREAD

**Issue by mnikitin** [MccreeZhao/QAMFace#6]
Hello and thanks for your work!

Did you try to use cross-entropy loss with your QAAM head? If yes, what were the results compared to the focal-loss?

**Comment by MccreeZhao** [comment]
Hi~
I didn't try QAM head + CELoss. However, I do have compared CELoss with Focal-Loss on ArcFace head and the results indicate that Focal-Loss is better than CELoss.

**Comment by mnikitin** [comment]
That's interesting. Thanks!
